name: coinbase_cloud_advanced_trade_client_example
description: An example of how to use the coinbase_cloud_advanced_trade_client package.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  coinbase_cloud_advanced_trade_client:
    path: ../
