name: coinbase_cloud_advanced_trade_client
description: Dart Client for building applications that interact with the Coinbase Cloud Advanced Trade & Pro Crypto
  Exchange APIs for automated trading and managing accounts.
version: 0.6.1
repository: https://github.com/HairstonSolutions/coinbase-cloud-advanced-trade-dart-client

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  http: ^1.2.1
  jose: ^0.3.5
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.2
  mockito: ^5.4.4
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

false_secrets:
  - test/test_constants.dart
