name: get_products
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  coinbase_pro_sdk: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
